/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VstockRouteImport } from './routes/vstock'
import { Route as UnitTrustsRouteImport } from './routes/unit-trusts'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as RedeemRouteImport } from './routes/redeem'
import { Route as RatesRouteImport } from './routes/rates'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MoreRouteImport } from './routes/more'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as InvestSummaryRouteImport } from './routes/invest-summary'
import { Route as InvestRouteImport } from './routes/invest'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as BankAccountsRouteImport } from './routes/bank-accounts'
import { Route as AnalyticalRouteImport } from './routes/analytical'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnitTrustsIndexRouteImport } from './routes/unit-trusts.index'
import { Route as HelpIndexRouteImport } from './routes/help.index'
import { Route as UnitTrustsSubAccountIdRouteImport } from './routes/unit-trusts.$subAccountId'
import { Route as NotificationsSettingsRouteImport } from './routes/notifications.settings'
import { Route as HelpContactRouteImport } from './routes/help.contact'

const VstockRoute = VstockRouteImport.update({
  id: '/vstock',
  path: '/vstock',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitTrustsRoute = UnitTrustsRouteImport.update({
  id: '/unit-trusts',
  path: '/unit-trusts',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeemRoute = RedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesRoute = RatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestSummaryRoute = InvestSummaryRouteImport.update({
  id: '/invest-summary',
  path: '/invest-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestRoute = InvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const BankAccountsRoute = BankAccountsRouteImport.update({
  id: '/bank-accounts',
  path: '/bank-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticalRoute = AnalyticalRouteImport.update({
  id: '/analytical',
  path: '/analytical',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitTrustsIndexRoute = UnitTrustsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UnitTrustsRoute,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HelpRoute,
} as any)
const UnitTrustsSubAccountIdRoute = UnitTrustsSubAccountIdRouteImport.update({
  id: '/$subAccountId',
  path: '/$subAccountId',
  getParentRoute: () => UnitTrustsRoute,
} as any)
const NotificationsSettingsRoute = NotificationsSettingsRouteImport.update({
  id: '/notifications/settings',
  path: '/notifications/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpContactRoute = HelpContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => HelpRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytical': typeof AnalyticalRoute
  '/bank-accounts': typeof BankAccountsRoute
  '/get-started': typeof GetStartedRoute
  '/help': typeof HelpRouteWithChildren
  '/invest': typeof InvestRoute
  '/invest-summary': typeof InvestSummaryRoute
  '/learn': typeof LearnRoute
  '/more': typeof MoreRoute
  '/profile': typeof ProfileRoute
  '/rates': typeof RatesRoute
  '/redeem': typeof RedeemRoute
  '/requests': typeof RequestsRoute
  '/transactions': typeof TransactionsRoute
  '/unit-trusts': typeof UnitTrustsRouteWithChildren
  '/vstock': typeof VstockRoute
  '/help/contact': typeof HelpContactRoute
  '/notifications/settings': typeof NotificationsSettingsRoute
  '/unit-trusts/$subAccountId': typeof UnitTrustsSubAccountIdRoute
  '/help/': typeof HelpIndexRoute
  '/unit-trusts/': typeof UnitTrustsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytical': typeof AnalyticalRoute
  '/bank-accounts': typeof BankAccountsRoute
  '/get-started': typeof GetStartedRoute
  '/invest': typeof InvestRoute
  '/invest-summary': typeof InvestSummaryRoute
  '/learn': typeof LearnRoute
  '/more': typeof MoreRoute
  '/profile': typeof ProfileRoute
  '/rates': typeof RatesRoute
  '/redeem': typeof RedeemRoute
  '/requests': typeof RequestsRoute
  '/transactions': typeof TransactionsRoute
  '/vstock': typeof VstockRoute
  '/help/contact': typeof HelpContactRoute
  '/notifications/settings': typeof NotificationsSettingsRoute
  '/unit-trusts/$subAccountId': typeof UnitTrustsSubAccountIdRoute
  '/help': typeof HelpIndexRoute
  '/unit-trusts': typeof UnitTrustsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytical': typeof AnalyticalRoute
  '/bank-accounts': typeof BankAccountsRoute
  '/get-started': typeof GetStartedRoute
  '/help': typeof HelpRouteWithChildren
  '/invest': typeof InvestRoute
  '/invest-summary': typeof InvestSummaryRoute
  '/learn': typeof LearnRoute
  '/more': typeof MoreRoute
  '/profile': typeof ProfileRoute
  '/rates': typeof RatesRoute
  '/redeem': typeof RedeemRoute
  '/requests': typeof RequestsRoute
  '/transactions': typeof TransactionsRoute
  '/unit-trusts': typeof UnitTrustsRouteWithChildren
  '/vstock': typeof VstockRoute
  '/help/contact': typeof HelpContactRoute
  '/notifications/settings': typeof NotificationsSettingsRoute
  '/unit-trusts/$subAccountId': typeof UnitTrustsSubAccountIdRoute
  '/help/': typeof HelpIndexRoute
  '/unit-trusts/': typeof UnitTrustsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytical'
    | '/bank-accounts'
    | '/get-started'
    | '/help'
    | '/invest'
    | '/invest-summary'
    | '/learn'
    | '/more'
    | '/profile'
    | '/rates'
    | '/redeem'
    | '/requests'
    | '/transactions'
    | '/unit-trusts'
    | '/vstock'
    | '/help/contact'
    | '/notifications/settings'
    | '/unit-trusts/$subAccountId'
    | '/help/'
    | '/unit-trusts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytical'
    | '/bank-accounts'
    | '/get-started'
    | '/invest'
    | '/invest-summary'
    | '/learn'
    | '/more'
    | '/profile'
    | '/rates'
    | '/redeem'
    | '/requests'
    | '/transactions'
    | '/vstock'
    | '/help/contact'
    | '/notifications/settings'
    | '/unit-trusts/$subAccountId'
    | '/help'
    | '/unit-trusts'
  id:
    | '__root__'
    | '/'
    | '/analytical'
    | '/bank-accounts'
    | '/get-started'
    | '/help'
    | '/invest'
    | '/invest-summary'
    | '/learn'
    | '/more'
    | '/profile'
    | '/rates'
    | '/redeem'
    | '/requests'
    | '/transactions'
    | '/unit-trusts'
    | '/vstock'
    | '/help/contact'
    | '/notifications/settings'
    | '/unit-trusts/$subAccountId'
    | '/help/'
    | '/unit-trusts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticalRoute: typeof AnalyticalRoute
  BankAccountsRoute: typeof BankAccountsRoute
  GetStartedRoute: typeof GetStartedRoute
  HelpRoute: typeof HelpRouteWithChildren
  InvestRoute: typeof InvestRoute
  InvestSummaryRoute: typeof InvestSummaryRoute
  LearnRoute: typeof LearnRoute
  MoreRoute: typeof MoreRoute
  ProfileRoute: typeof ProfileRoute
  RatesRoute: typeof RatesRoute
  RedeemRoute: typeof RedeemRoute
  RequestsRoute: typeof RequestsRoute
  TransactionsRoute: typeof TransactionsRoute
  UnitTrustsRoute: typeof UnitTrustsRouteWithChildren
  VstockRoute: typeof VstockRoute
  NotificationsSettingsRoute: typeof NotificationsSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vstock': {
      id: '/vstock'
      path: '/vstock'
      fullPath: '/vstock'
      preLoaderRoute: typeof VstockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unit-trusts': {
      id: '/unit-trusts'
      path: '/unit-trusts'
      fullPath: '/unit-trusts'
      preLoaderRoute: typeof UnitTrustsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redeem': {
      id: '/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof RedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates': {
      id: '/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof RatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest-summary': {
      id: '/invest-summary'
      path: '/invest-summary'
      fullPath: '/invest-summary'
      preLoaderRoute: typeof InvestSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest': {
      id: '/invest'
      path: '/invest'
      fullPath: '/invest'
      preLoaderRoute: typeof InvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-accounts': {
      id: '/bank-accounts'
      path: '/bank-accounts'
      fullPath: '/bank-accounts'
      preLoaderRoute: typeof BankAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytical': {
      id: '/analytical'
      path: '/analytical'
      fullPath: '/analytical'
      preLoaderRoute: typeof AnalyticalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unit-trusts/': {
      id: '/unit-trusts/'
      path: '/'
      fullPath: '/unit-trusts/'
      preLoaderRoute: typeof UnitTrustsIndexRouteImport
      parentRoute: typeof UnitTrustsRoute
    }
    '/help/': {
      id: '/help/'
      path: '/'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof HelpRoute
    }
    '/unit-trusts/$subAccountId': {
      id: '/unit-trusts/$subAccountId'
      path: '/$subAccountId'
      fullPath: '/unit-trusts/$subAccountId'
      preLoaderRoute: typeof UnitTrustsSubAccountIdRouteImport
      parentRoute: typeof UnitTrustsRoute
    }
    '/notifications/settings': {
      id: '/notifications/settings'
      path: '/notifications/settings'
      fullPath: '/notifications/settings'
      preLoaderRoute: typeof NotificationsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/contact': {
      id: '/help/contact'
      path: '/contact'
      fullPath: '/help/contact'
      preLoaderRoute: typeof HelpContactRouteImport
      parentRoute: typeof HelpRoute
    }
  }
}

interface HelpRouteChildren {
  HelpContactRoute: typeof HelpContactRoute
  HelpIndexRoute: typeof HelpIndexRoute
}

const HelpRouteChildren: HelpRouteChildren = {
  HelpContactRoute: HelpContactRoute,
  HelpIndexRoute: HelpIndexRoute,
}

const HelpRouteWithChildren = HelpRoute._addFileChildren(HelpRouteChildren)

interface UnitTrustsRouteChildren {
  UnitTrustsSubAccountIdRoute: typeof UnitTrustsSubAccountIdRoute
  UnitTrustsIndexRoute: typeof UnitTrustsIndexRoute
}

const UnitTrustsRouteChildren: UnitTrustsRouteChildren = {
  UnitTrustsSubAccountIdRoute: UnitTrustsSubAccountIdRoute,
  UnitTrustsIndexRoute: UnitTrustsIndexRoute,
}

const UnitTrustsRouteWithChildren = UnitTrustsRoute._addFileChildren(
  UnitTrustsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticalRoute: AnalyticalRoute,
  BankAccountsRoute: BankAccountsRoute,
  GetStartedRoute: GetStartedRoute,
  HelpRoute: HelpRouteWithChildren,
  InvestRoute: InvestRoute,
  InvestSummaryRoute: InvestSummaryRoute,
  LearnRoute: LearnRoute,
  MoreRoute: MoreRoute,
  ProfileRoute: ProfileRoute,
  RatesRoute: RatesRoute,
  RedeemRoute: RedeemRoute,
  RequestsRoute: RequestsRoute,
  TransactionsRoute: TransactionsRoute,
  UnitTrustsRoute: UnitTrustsRouteWithChildren,
  VstockRoute: VstockRoute,
  NotificationsSettingsRoute: NotificationsSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
